on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '25'
          rebar3-version: '3.20.0'
      - run: sudo apt update && sudo apt install -y make gcc git libssl-dev
      - run: DIAGNOSTIC=1 rebar3 get-deps && rebar3 ct && rebar3 dialyzer && rebar3 lint
